"""add device_status

Revision ID: c51e9d80a380
Revises: bbdafb946768
Create Date: 2026-03-16 16:49:16.652336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c51e9d80a380'
down_revision: Union[str, Sequence[str], None] = 'bbdafb946768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_status', sa.Column('last_payload_ok', sa.Boolean(), nullable=True))
    op.add_column('device_status', sa.Column('queue_size', sa.Integer(), nullable=True))
    op.add_column('device_status', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_device_status_device_id'), 'device_status', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_status_id'), 'device_status', ['id'], unique=False)
    op.create_index(op.f('ix_raw_measurements_timestamp'), 'raw_measurements', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_measurements_timestamp'), table_name='raw_measurements')
    op.drop_index(op.f('ix_device_status_id'), table_name='device_status')
    op.drop_index(op.f('ix_device_status_device_id'), table_name='device_status')
    op.drop_column('device_status', 'updated_at')
    op.drop_column('device_status', 'queue_size')
    op.drop_column('device_status', 'last_payload_ok')
    # ### end Alembic commands ###
